- name: copy install files
  copy:
    src: ../files/starccm/siemens.tar.gz
    dest: /tmp/siemens.tar.gz

- name: unzip
  command: tar -xvzf /tmp/siemens.tar.gz -C /opt
 
- name: add to PATH in bash.bashrc
  ansible.builtin.lineinfile:
    path: /etc/bash.bashrc
    regexp: '^export PATH="$PATH:/opt/Siemens/20.04.007-R8/STAR-CCM+20.04.007-R8/star/bin/:/opt/Siemens/20.04.007-R8/STAR-View+20.04.007/bin/"'
    line: export PATH="$PATH:/opt/Siemens/20.04.007-R8/STAR-CCM+20.04.007-R8/star/bin/:/opt/Siemens/20.04.007-R8/STAR-View+20.04.007/bin/"

- name: remove install files
  file:
    path: /tmp/siemens.tar.gz
    state: absent
