- name: Install flatpak
  apt:
    name: flatpak
    state: present
    update_cache: yes

- name: add remote flathub
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install prusa slicer
  flatpak:
    name: com.prusa3d.PrusaSlicer
