- name: Install python
  apt:
    name: python3
    state: present
    update_cache: yes

- name: Install numpy
  apt:
    name: python3-numpy
    state: present
    update_cache: yes

- name: Install matplotlib
  apt:
    name: python3-matplotlib
    state: present
    update_cache: yes

- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes
