- name: Update and upgrade apt packages
  hosts: li148
  become: true
  tasks:
    - name: apt upgrade
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
